---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-source-integration-tools
  labels:
    app: open-source-integration-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-source-integration-tools
  template:
    metadata:
      labels:
        app: open-source-integration-tools
    spec:
      containers:
        - name: open-source-integration-tools
          image: jiminb/open-source-integration-tools:v0.1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: "/actuator/health"
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: "/actuator/health"
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
