---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: scan-request-management
  labels:
    app: scan-request-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scan-request-management
  template:
    metadata:
      labels:
        app: scan-request-management
    spec:
      containers:
        - name: scan-request-management
          image: username/scan-request-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-source-integration-tools
  labels:
    app: open-source-integration-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-source-integration-tools
  template:
    metadata:
      labels:
        app: open-source-integration-tools
    spec:
      containers:
        - name: open-source-integration-tools
          image: username/open-source-integration-tools:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: scan-request-management
  labels:
    app: scan-request-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: scan-request-management


---


apiVersion: v1
kind: Service
metadata:
  name: open-source-integration-tools
  labels:
    app: open-source-integration-tools
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: open-source-integration-tools

