---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scan-request-management
  labels:
    app: scan-request-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scan-request-management
  template:
    metadata:
      labels:
        app: scan-request-management
    spec:
      containers:
        - name: scan-request-management
          image: jiminb/scan-request-management:v0.1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: "/actuator/health"
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: "/actuator/health"
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
